##This script correlates and plots the relationship between lfp electrode impedance and the offset differences
#dependencies: needs dataframe e.g. "dataframe_lag_shift_impedance_num3GoNOGofrom channel0to21.csv" generated by Lag_testing.py

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import Normalize
import os
import sys
from scipy.stats import ttest_ind
import statsmodels.formula.api as smf
parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(parent_dir)
from config import DATA_PATH
path = DATA_PATH

savepath=path+"/Figures/"
if not os.path.exists(savepath):
    os.makedirs(savepath)
#define task(s), in the paper we use GoNOGo+sync_test combined
#task_category="GoNOGo"
task_category=["GoNOGo","sync_test"]

#task_category="sync_test"
#relevant eeg channels
eeg_channels_nums=[0,21]
#impedance category selected min=1, mean=2 or max=3 of channel pairs incase of directional leads
impedance_category="ratio"
#read in datafraem
lag=np.array([])
lfp_n=np.array([])
participants=np.array([])
#combine data from both tasks
for cat in task_category:
    lag_dataframe=pd.read_csv(path+"dataframe_lag_shift_impedance_num_"+impedance_category+"_"+cat+"from channel"+str(eeg_channels_nums[0])+" to "+str(eeg_channels_nums[1])+".csv")
    print(lag_dataframe.columns, len(lag_dataframe))

    # Extract the data X= the offset difference in milliseconds, Y= the impedance (averaged incase of inconsistent recording lfp channel pairs selected)
    lag_here = lag_dataframe["lag difference ms"]
    lfp_n_here = lag_dataframe["num lfp electrodes"]
    participant_here=lag_dataframe["participant"]
    lag=np.concatenate((lag,np.array(lag_here)))
    lfp_n=np.concatenate((lfp_n,np.array(lfp_n_here)))
    participants = np.concatenate((participants,np.array(participant_here)))
combined_df=pd.DataFrame(
    {'participant': participants,
     'lag difference ms': lag,
     'num lfp electrodes': lfp_n
    })  
unique_lfp = np.sort(np.unique(lfp_n))

# group data
grouped_data = [lag[lfp_n == n] for n in unique_lfp]

# Fit mixed-effects model with lag difference in ms and number of lfp electrodes
lmm = smf.mixedlm(
    "Q('lag difference ms') ~ Q('num lfp electrodes')",
    combined_df,
    groups=combined_df["participant"]
)

lmm_result = lmm.fit()

print(lmm_result.summary())
# ----------------------------------
# Perform posthoc T-tests (pairwise)

print("Pairwise t-tests (lag precision):")
print("----------------------------------")

for i in range(len(unique_lfp)):
    for j in range(i + 1, len(unique_lfp)):
        g1 = lag[lfp_n == unique_lfp[i]]
        g2 = lag[lfp_n == unique_lfp[j]]

        t, p = ttest_ind(g1, g2, equal_var=False)
        print(
            f"{unique_lfp[i]} vs {unique_lfp[j]} LFP electrodes: "
            f"t = {t:.2f}, p = {p:.3g}"
        )

# ----------------------------------
# Plot lag differences per recording electrode number in a boxplot

fig, ax = plt.subplots(figsize=(6, 4))

#create boxplots
bp = ax.boxplot(
    grouped_data,
    patch_artist=True,
    showfliers=False,
    labels=unique_lfp
)

# colors
cmap = plt.get_cmap("Set2")
colors = [cmap(i) for i in range(len(unique_lfp))]

for patch, color in zip(bp["boxes"], colors):
    patch.set_facecolor(color)
    patch.set_alpha(0.4)

# jittered scatter of the single data points
for i, data in enumerate(grouped_data):
    x_center = i + 1
    jitter = 0.18
    x_j = x_center + np.random.uniform(-jitter, jitter, size=len(data))

    ax.scatter(
        x_j, data,
        color=colors[i],
        edgecolor="k",
        s=50,
        alpha=0.8
    )

# set plot layout
ax.set_xlabel("Number of LFP contacts", fontsize=16)
ax.set_ylabel("Lag precision (ms)", fontsize=16)

ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

ax.yaxis.grid(True, linestyle="--", alpha=0.4)

ax.tick_params(axis="x", labelsize=15)
ax.tick_params(axis="y", labelsize=15)
plt.yticks([0,5,10,15,20,25,30],[0,"",10,"",20,"",30])
plt.tight_layout()
#save the figure
plt.savefig(
    savepath + f"Lag_precision_by_LFP_contacts_{task_category}.pdf",
    format="pdf",
    dpi=1200
)

plt.show()
