##This script correlates and plots the relationship between lfp electrode impedance and the offset differences
#dependencies: needs dataframe e.g. "dataframe_lag_shift_impedance_num3GoNOGofrom channel0to21.csv" generated by Lag_testing.py

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import Normalize
import os
import sys
from scipy.stats import linregress
parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(parent_dir)
from config import DATA_PATH
path = DATA_PATH

savepath=path+"/Figures/"
if not os.path.exists(savepath):
    os.makedirs(savepath)
#define task(s), in the paper we use GoNOGo+sync_test combined
task_category="GoNOGo"
task_category=["GoNOGo","sync_test"]
#task_category="sync_test"
#relevant eeg channels
eeg_channels_nums=[0,21]
#impedance category selected min=1, mean=2 or max=3 of channel pairs incase of directional leads
impedance_category="ratio"
#read in datafraem
x=np.array([])
y=np.array([])
#concatenate data from both tasks
for cat in task_category:
    lag_dataframe=pd.read_csv(path+"dataframe_lag_shift_impedance_num_"+impedance_category+"_"+cat+"from channel"+str(eeg_channels_nums[0])+" to "+str(eeg_channels_nums[1])+".csv")

    #check if the lfp channels selected for optimal synchronization are consistent if not we take the mean of the respective recording channel pairs, we save this information in addtional columns of the dataframe
    if task_category=="sync_test":
        lag_dataframe["consistent lfp channel"] = (lag_dataframe["channel lfp 1"].eq(lag_dataframe["channel lfp 2"]) & lag_dataframe["channel lfp 2"].eq(lag_dataframe["channel lfp 3"])).astype(int)
        lag_dataframe["mean impedance"]=lag_dataframe[["impedance lfp 1", "impedance lfp 2", "impedance lfp 3"]].apply(pd.to_numeric, errors="coerce").mean(axis=1)
        if impedance_category=="ratio":
            lag_dataframe["mean impedance"] = lag_dataframe["mean impedance"].apply(lambda r: max(r, 1/r))
    else:
        lag_dataframe["consistent lfp channel"] = (lag_dataframe["channel lfp 1"].eq(lag_dataframe["channel lfp 2"])).astype(int)
        lag_dataframe["mean impedance"]=lag_dataframe[["impedance lfp 1", "impedance lfp 2"]].apply(pd.to_numeric, errors="coerce").mean(axis=1)
        if impedance_category=="ratio":
            lag_dataframe["mean impedance"] = lag_dataframe["mean impedance"].apply(lambda r: max(r, 1/r))


    # Extract the data X= the offset difference in milliseconds, Y= the impedance (averaged incase of inconsistent recording lfp channel pairs selected)
    x_here = lag_dataframe["lag difference ms"]
    y_here = lag_dataframe["mean impedance"]
    x=np.concatenate((x,np.array(x_here)))
    y=np.concatenate((y,np.array(y_here)))
# jitter for plot
jitter_strength = 0.05    # adjust as needed
y_jittered = y + np.random.uniform(-jitter_strength, jitter_strength, size=len(y))

# Fit regression between lag difference and impedance
slope, intercept, r, p, se = linregress(x, y)
line_x = np.linspace(np.min(x), np.max(x), 200)
line_y = slope * line_x + intercept

# Use Set2 colormap like your boxplot design
cmap = plt.get_cmap("Set2")
point_color = cmap(0)        # first color in Set2
line_color = cmap(1)         # second color in Set2

plt.figure(figsize=(6, 4))

# Scatter the single datapoints for each recording
plt.scatter(
    x, y_jittered,
    color=point_color,
    edgecolor="k",
    s=60,
    alpha=0.8
)

# plot the Regression line
plt.plot(
    line_x, line_y,
    linewidth=2.5,
    color=line_color
)

# Set the y and x-axis labels
plt.xlabel("Offset difference (ms)", fontsize=16)
plt.ylabel("Impedance ratio", fontsize=16)
print(f"r = {r:.2f}, p = {p:.3g}")

# set plot layout
ax = plt.gca()
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

plt.grid(True, linestyle="--", alpha=0.4)
#ax.set_yticks([3000,4000,5000,6000,7000],["",4000,"",6000,""],fontsize=15)
ax.set_xticks([0,10,20,30],[0,10,20,30],fontsize=15)



plt.tight_layout()
#save the figure
plt.savefig(savepath+"Correlation_impedance_lag_difference_num"+str(impedance_category)+str(task_category)+".pdf", format='pdf', dpi=1200) 

plt.show()
