##This script plots offset differences per participant as well as by recording modality
# prints the mean lags for each recording modality
# dependencies: needs dataframe "dataframe_lag_shift_single_channelGoNOGofrom channel0 to 21.csv" generated by Lag_testing_single_channels.py


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import Normalize
from matplotlib.lines import Line2D
from matplotlib.colors import ListedColormap

import sys
import os
parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(parent_dir)
from config import DATA_PATH
path = DATA_PATH

savepath=path+"/Figures/"
if not os.path.exists(savepath):
    os.makedirs(savepath)
#particpants included in this plot
participant_list=["P01","P02","P03","P04","P05","P06","P07","P08","P09","P10","P11"]
eeg_channels_nums=[0,21]
#this script is specific for GoNOGo
task_category="GoNOGo"
impedance_category="diff"
#load the right dataframe with the data
lag_dataframe=pd.read_csv(path+"dataframe_lag_shift_impedance_num_"+impedance_category+"_"+task_category+"from channel"+str(eeg_channels_nums[0])+" to "+str(eeg_channels_nums[1])+".csv")
plot_per_recording_number=False
plot_per_number_lfp_electrodes=False

#extract the relevant columns
list_participant = np.array(lag_dataframe["participant"], dtype=str)
list_lag_difference = np.array(lag_dataframe["lag difference ms"], dtype=float)
list_recording_modality = np.array(lag_dataframe["recording_modality"], dtype=str)

# Convert participant IDs "P01" → 1, 14, etc.
list_int_participant = np.array([int(p[1:]) for p in list_participant])

# Map modality strings → integers (automatic)

unique_modalities=["indef","On","treat"]
modality_to_int = {m: i for i, m in enumerate(unique_modalities)}
modality_ints = np.array([modality_to_int[m] for m in list_recording_modality])


fig,ax=plt.subplots(figsize=(6, 4))
# color setup


cmap = plt.get_cmap("tab10")
norm = Normalize(vmin=0, vmax=3)

colors = [cmap(norm(i)) for i in (0, 2, 3)]
cmap=ListedColormap(colors)
norm = Normalize(vmin=0, vmax=len(unique_modalities)-1)
jitter_amount = 0.21
x_jittered = list_int_participant + np.random.uniform(
    -jitter_amount, jitter_amount, size=len(list_int_participant)
)

plt.scatter(
        x_jittered,
        list_lag_difference,
        c=modality_ints,
        s=70,
        cmap=cmap,
        norm=norm,
        edgecolor="k"
    )


ax.yaxis.grid(True, linestyle="--", alpha=0.4)
list_unique_participant=np.unique(list_participant)
ax.set_xticks(range(1,len(participant_list)+1),participant_list,size=15)
ax.set_yticks([0,5,10,15,20,25,30],[0,"",10," ",20," ",30], size=15)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
plt.xlabel("Participant",size=16)
plt.ylabel("Offset Difference (ms)",size=16)

plt.tight_layout()
#save the figure
#plt.savefig(savepath+"Lags_per_participant"+task_category+"recording number"+str(plot_per_recording_number)+".pdf", format='pdf', dpi=1200) 

# ------------------------------------------------
# BOX PLOT GROUPED BY MODALITY
fig, ax2 = plt.subplots()

    # Original modality-based data
modal_box_data = [
        list_lag_difference[modality_ints == i]
        for i in range(len(unique_modalities))
    ]

# Add ALL category to the end
all_data = list_lag_difference
box_data = modal_box_data + [all_data]

labels_with_all = list(unique_modalities) + ["all"]

# create boxplots
bp = ax2.boxplot(
        box_data,
        patch_artist=True,
        labels=labels_with_all, showfliers=False
    )

# colors: modalities use cmap, ALL gets gray at the end
ax2_colors = [cmap(norm(i)) for i in range(len(unique_modalities))] + ["#cccccc"]

for patch, color in zip(bp["boxes"], ax2_colors):
        patch.set_facecolor(color)
        patch.set_alpha(0.4)

# jittered scatter for each category
for i, data in enumerate(box_data):
        x_center = i + 1
        jitter_amount=0.18
        x_j = x_center + np.random.uniform(-jitter_amount, jitter_amount, size=len(data))
        ax2.scatter(x_j, data, color=ax2_colors[i], edgecolor="k",s=50)

# plotting layout
ax2.spines["top"].set_visible(False)
ax2.spines["right"].set_visible(False)

ax2.yaxis.grid(True, linestyle="--", alpha=0.4)
ax2.set_yticks([0,5,10,15,20,25,30],[0,"",10," ",20," ",30], size=15)
ax2.set_xticks([1,2,3,4],unique_modalities+["all"], size=15)

plt.xlabel("Recording modality",size=17)
plt.ylabel("Offset difference (ms)",size=17)
plt.tight_layout()
plt.savefig(savepath+"Lags_per_recording_modality"+task_category+".pdf", format='pdf', dpi=1200) 

#summarize and print lag differences by recording modality
print("Overall_Mean:",lag_dataframe["lag difference ms"].mean(),"_std:_",lag_dataframe["lag difference ms"].std())

df_on=lag_dataframe[lag_dataframe["recording_modality"]=="On"]
print("On_Mean:",df_on["lag difference ms"].mean(),"_std:_",df_on["lag difference ms"].std())

df_indef=lag_dataframe[lag_dataframe["recording_modality"]=="indef"]
print("Indef_Mean",df_indef["lag difference ms"].mean(),"_std:_",df_indef["lag difference ms"].std())
df_treat=lag_dataframe[lag_dataframe["recording_modality"]=="treat"]
print("Treat_Mean:",df_treat["lag difference ms"].mean(),"_std:_",df_treat["lag difference ms"].std())