##This script plots and computes the releationship between lag offset and recording length 
# performs statistical testing
# dependencies: needs dataframe "dataframe_lag_shift_single_channelsync_testfrom channel0 to 21.csv" generated by Lag_testing_single_channels.py
#               needs dataframe "dataframe_recording_lengtnGoNOGofrom channel.csv" generated by compute_recording_length_go_nogo.py
#

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import Normalize

from scipy.stats import linregress
from scipy.stats import ttest_ind
import statsmodels.formula.api as smf


import sys
import os
parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(parent_dir)
from config import DATA_PATH
path = DATA_PATH

savepath=path+"/Figures/"
if not os.path.exists(savepath):
    os.makedirs(savepath)
#this script is specific for GoNOGo 
task_category="GoNOGo"
#load the right dataframe with the data
eeg_channels_nums=[0,21]
impedance_category="diff"
#load the dataframe with GoNOGo recording lenghts
rl_df=pd.read_csv(path+"dataframe_recording_length"+task_category+"from channel.csv")   
#load the dataframe with offset differences
lag_dataframe=pd.read_csv(path+"dataframe_lag_shift_impedance_num_"+impedance_category+"_"+task_category+"from channel"+str(eeg_channels_nums[0])+" to "+str(eeg_channels_nums[1])+".csv")
#combine both dataframes
combined_df=pd.merge(rl_df,lag_dataframe,on="recording")


#----------------------------------------
#plot the recording length against the lag difference


# Extract the data X= the offset difference in milliseconds, Y= recording length in minutes

x = np.array(combined_df["lag difference ms"], dtype=float)
y = np.array(combined_df["lfp recording length"], dtype=float)

# Fit regression between lag difference and recording length
slope, intercept, r, p, se = linregress(x, y)
line_x = np.linspace(np.min(x), np.max(x), 200)
line_y = slope * line_x + intercept

# Use Set2 colormap like your boxplot design
cmap = plt.get_cmap("Set2")
point_color = cmap(0)        # first color in Set2
line_color = cmap(1)         # second color in Set2

plt.figure(figsize=(7, 4))

# Scatter the single datapoints for each recording

plt.scatter(
    x, y,
    color=point_color,
    edgecolor="k",
    s=60,
    alpha=0.8
)

# Plot the regression line
plt.plot(
    line_x, line_y,
    linewidth=2.5,
    color=line_color
)

# Set the y and x-axis labels
plt.xlabel("Lag difference (ms)", fontsize=16)
plt.ylabel("LFP recording length", fontsize=16)
print(f"r = {r:.2f}, p = {p:.3g}")
# set plot layout
ax = plt.gca()
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

plt.grid(True, linestyle="--", alpha=0.4)
ax.set_yticks([4,4.5,5,5.5],[4,4.5,5,5.5],fontsize=15)
ax.set_xticks([0,10,20,30],[0,10,20,30],fontsize=15)

#save the figure
plt.savefig(savepath+"Correlation_recording_length_lag_difference"+task_category+".pdf", format='pdf', dpi=1200)
plt.tight_layout()
plt.show()


