##This script plots mean offset for synchronization with one single eeg channel on a topomap of the head
# dependencies: needs dataframe "dataframe_lag_shift_single_channelsync_testfrom channel0 to 21.csv" generated by Lag_testing_single_channels.py
#               needs a list of the eeg channel names eeg_channels.npy

import numpy as np
import matplotlib.pyplot as plt
import mne
from mne.viz import plot_topomap
import sys
import os
import pandas as pd

import matplotlib.colors as mcolors

parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(parent_dir)
from config import DATA_PATH
path = DATA_PATH

#create a folder Figure in the data folder to save the images
savepath=path+"/Figures/"
if not os.path.exists(savepath):
    os.makedirs(savepath)

#load the dataframe computed by Lag_testing_single_channels with mean lags per channel
t_score_dataframe=pd.read_csv(path+"dataframe_lag_shift_single_channelsync_testfrom channel0 to 21.csv")
#load a list of eeg_channels
eeg_channels=np.load(path+"/P01/sync_test/P01sync_test_0mA/eeg_channels.npy")

df=t_score_dataframe
df["channel"] = df["channel"]
#clean the eeg channel names to match those used in the mne package
df["channel_clean"]=eeg_channels[0:21]
df["channel_clean"]=df["channel_clean"].str.replace("EEG ", "", regex=False)

#Define channels to plot (20–21 channels)

channels_10_20 = [
    'Fp1','Fp2','F3','F4','C3','C4','P3','P4','O1','O2',
    'F7','F8','T3','T4','T5','T6','Fz','Cz','Pz','M1','M2'
]
 
# the mean _lags are saved in column "mean_lag"
mean_lags = np.array(df["mean_lag"])

#Create MNE info & montage

info = mne.create_info(ch_names=channels_10_20, sfreq=100, ch_types='eeg')
montage = mne.channels.make_standard_montage('standard_1020')
info.set_montage(montage)

#define a color map
base_cmap = plt.cm.afmhot
colors = base_cmap(np.linspace(0, 1, 256))
colors[:, 3] = np.linspace(0.85, 1.0, 256)  # alpha from 0.6 → 1
hot_alpha = mcolors.ListedColormap(colors)

# Create the topoplot
fig, ax = plt.subplots(figsize=(8, 8))

vmin = np.nanpercentile(mean_lags, 1)
vmax = np.nanpercentile(mean_lags, 90)

# Plot topomap without names
plot_topomap(
    mean_lags,
    info,
    axes=ax,
    show=False,
    names=None,
    cmap=hot_alpha,
    vlim=(vmin, vmax),
    res=64
)

# Get 2D channel positions
pos = np.array([info['chs'][info.ch_names.index(ch)]['loc'][:2] for ch in channels_10_20])
x, y = pos[:, 0], pos[:, 1]

# Function to compute brightness of an RGBA color
def brightness(rgba):
    r, g, b, _ = rgba
    return 0.299*r + 0.587*g + 0.114*b  # luminance, 0-1

# Normalize t-values to 0-1 for the colormap
norm = mcolors.Normalize(vmin=vmin, vmax=vmax)
#create colors to be visible either black or white
for ch, xi, yi, val in zip(channels_10_20, x, y, mean_lags):
    if ch in ['Fp1', 'Fp2','F7']:
        color = 'black'  # force black for FP1 and FP2
    else:
        rgba = hot_alpha(norm(val))
        color = 'black' if brightness(rgba) > 0.5 else 'white'
    ax.text(xi, yi, ch, color=color, fontsize=18, ha='center', va='center')


#save the plot
#plt.savefig(savepath+"t_score_topomap"+string_here+".pdf", format='pdf', dpi=1200) 

plt.show()



