##This script plots t-values describing the power difference between the artefact and non-artefact signal parts
# dependencies: needs dataframe "dataframe_eeg_artefact_testing.csv" generated by Artefact_significance_test_eeg.py
#               needs dataframe "dataframe_lfp_artefact_testing.csv" generated by Artefact_significance_test_eeg.py

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
import sys
parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(parent_dir)
from config import DATA_PATH
path = DATA_PATH

#create a folder Figure in the data folder to save the images
savepath=path+"/Figures/"
if not os.path.exists(savepath):
    os.makedirs(savepath)
#load the eeg and lfp significance testing dataframe generated by skripts Artefact_significance_test_eeg and Artefact_significane_test_lfp
eeg_dataframe=pd.read_csv(path+"dataframe_eeg_artefact_testing.csv")
lfp_dataframe=pd.read_csv(path+"dataframe_lfp_artefact_testing.csv")

#extract the relevant t-value columns from the respective dataframes
t_lfp=np.array(lfp_dataframe["t-value"])
t_eeg = np.array(eeg_dataframe["t-value"])


#generate a figure and plot boxplots for the lfp and eeg data
plt.figure(figsize=(7, 5))
ax=plt.subplot(111)
positions = [1, 2]
plt.boxplot(
    [t_lfp,t_eeg
     ],
     positions=positions,
    labels=["LFP","EEG"],
    medianprops=dict(linestyle='-', linewidth=2, color='black')
)

plt.title("")
plt.ylabel("T-value", size=16)
ax.tick_params(axis='both', which='major', labelsize=14.5)
ax.spines[['right', 'top']].set_visible(False)


datasets = [
    t_lfp,t_eeg
]

#add single t-values as jittered points
col_arr=["orange","blue"]
for i, data in enumerate(datasets):
    jitter = np.random.normal(0, 0.06, size=len(data))
    plt.scatter(np.ones(len(data)) * positions[i] + jitter,
                data, alpha=0.7, c=col_arr[i],s=25)
ax.yaxis.grid(True, linestyle='--', alpha=0.3)
plt.yscale('linear')

ax.set_yticks([-80,-70,-60,-50,-40,-30,-20,-10,0],["","","",-50,"","","","",0],size=15)
#save the figure
plt.savefig(savepath+"Baseline_vs_Artefact_t-value.pdf", format='pdf', dpi=1200) 
plt.show()




